// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema;

///<summary>
/// See <a href="https://corefork.telegram.org/constructor/botVerifierSettings" />
///</summary>
[TlObject(0xb0cd6617)]
public sealed class TBotVerifierSettings : IBotVerifierSettings
{
    public uint ConstructorId => 0xb0cd6617;
    public BitArray Flags { get; set; } = new BitArray(32);
    public bool CanModifyCustomDescription { get; set; }
    public long Icon { get; set; }
    public string Company { get; set; }
    public string? CustomDescription { get; set; }

    public void ComputeFlag()
    {
        if (CanModifyCustomDescription) { Flags[1] = true; }
        if (CustomDescription != null) { Flags[0] = true; }
    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Flags);
        writer.Write(Icon);
        writer.Write(Company);
        if (Flags[0]) { writer.Write(CustomDescription); }
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        Flags = reader.ReadBitArray();
        if (Flags[1]) { CanModifyCustomDescription = true; }
        Icon = reader.ReadInt64();
        Company = reader.ReadString();
        if (Flags[0]) { CustomDescription = reader.ReadString(); }
    }
}