// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema.Channels;

///<summary>
/// See <a href="https://corefork.telegram.org/method/channels.updatePaidMessagesPrice" />
///</summary>
[TlObject(0xfc84653f)]
public sealed class RequestUpdatePaidMessagesPrice : IRequest<MyTelegram.Schema.IUpdates>
{
    public uint ConstructorId => 0xfc84653f;
    public MyTelegram.Schema.IInputChannel Channel { get; set; }
    public long SendPaidMessagesStars { get; set; }

    public void ComputeFlag()
    {

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Channel);
        writer.Write(SendPaidMessagesStars);
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        Channel = reader.Read<MyTelegram.Schema.IInputChannel>();
        SendPaidMessagesStars = reader.ReadInt64();
    }
}
