// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema;

///<summary>
/// See <a href="https://corefork.telegram.org/constructor/monoForumDialog" />
///</summary>
[TlObject(0x64407ea7)]
public sealed class TMonoForumDialog : ISavedDialog
{
    public uint ConstructorId => 0x64407ea7;
    public BitArray Flags { get; set; } = new BitArray(32);
    public bool UnreadMark { get; set; }
    public MyTelegram.Schema.IPeer Peer { get; set; }
    public int TopMessage { get; set; }
    public int ReadInboxMaxId { get; set; }
    public int ReadOutboxMaxId { get; set; }
    public int UnreadCount { get; set; }
    public int UnreadReactionsCount { get; set; }
    public MyTelegram.Schema.IDraftMessage? Draft { get; set; }

    public void ComputeFlag()
    {
        if (UnreadMark) { Flags[3] = true; }
        if (Draft != null) { Flags[1] = true; }
    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Flags);
        writer.Write(Peer);
        writer.Write(TopMessage);
        writer.Write(ReadInboxMaxId);
        writer.Write(ReadOutboxMaxId);
        writer.Write(UnreadCount);
        writer.Write(UnreadReactionsCount);
        if (Flags[1]) { writer.Write(Draft); }
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        Flags = reader.ReadBitArray();
        if (Flags[3]) { UnreadMark = true; }
        Peer = reader.Read<MyTelegram.Schema.IPeer>();
        TopMessage = reader.ReadInt32();
        ReadInboxMaxId = reader.ReadInt32();
        ReadOutboxMaxId = reader.ReadInt32();
        UnreadCount = reader.ReadInt32();
        UnreadReactionsCount = reader.ReadInt32();
        if (Flags[1]) { Draft = reader.Read<MyTelegram.Schema.IDraftMessage>(); }
    }
}