// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema.Payments;

///<summary>
/// See <a href="https://corefork.telegram.org/method/payments.getResaleStarGifts" />
///</summary>
[TlObject(0x7a5fa236)]
public sealed class RequestGetResaleStarGifts : IRequest<MyTelegram.Schema.Payments.IResaleStarGifts>
{
    public uint ConstructorId => 0x7a5fa236;
    public BitArray Flags { get; set; } = new BitArray(32);
    public bool SortByPrice { get; set; }
    public bool SortByNum { get; set; }
    public long? AttributesHash { get; set; }
    public long GiftId { get; set; }
    public TVector<MyTelegram.Schema.IStarGiftAttributeId>? Attributes { get; set; }
    public string Offset { get; set; }
    public int Limit { get; set; }

    public void ComputeFlag()
    {
        if (SortByPrice) { Flags[1] = true; }
        if (SortByNum) { Flags[2] = true; }
        if (/*AttributesHash != 0 &&*/ AttributesHash.HasValue) { Flags[0] = true; }
        if (Attributes?.Count > 0) { Flags[3] = true; }

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Flags);
        if (Flags[0]) { writer.Write(AttributesHash.Value); }
        writer.Write(GiftId);
        if (Flags[3]) { writer.Write(Attributes); }
        writer.Write(Offset);
        writer.Write(Limit);
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        Flags = reader.ReadBitArray();
        if (Flags[1]) { SortByPrice = true; }
        if (Flags[2]) { SortByNum = true; }
        if (Flags[0]) { AttributesHash = reader.ReadInt64(); }
        GiftId = reader.ReadInt64();
        if (Flags[3]) { Attributes = reader.Read<TVector<MyTelegram.Schema.IStarGiftAttributeId>>(); }
        Offset = reader.ReadString();
        Limit = reader.ReadInt32();
    }
}
