// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema.Payments;

///<summary>
/// See <a href="https://corefork.telegram.org/method/payments.upgradeStarGift" />
///</summary>
[TlObject(0xaed6e4f5)]
public sealed class RequestUpgradeStarGift : IRequest<MyTelegram.Schema.IUpdates>
{
    public uint ConstructorId => 0xaed6e4f5;
    public BitArray Flags { get; set; } = new BitArray(32);
    public bool KeepOriginalDetails { get; set; }
    public MyTelegram.Schema.IInputSavedStarGift Stargift { get; set; }

    public void ComputeFlag()
    {
        if (KeepOriginalDetails) { Flags[0] = true; }

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Flags);
        writer.Write(Stargift);
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        Flags = reader.ReadBitArray();
        if (Flags[0]) { KeepOriginalDetails = true; }
        Stargift = reader.Read<MyTelegram.Schema.IInputSavedStarGift>();
    }
}
