// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema.Payments;

///<summary>
/// See <a href="https://corefork.telegram.org/method/payments.toggleStarGiftsPinnedToTop" />
///</summary>
[TlObject(0x1513e7b0)]
public sealed class RequestToggleStarGiftsPinnedToTop : IRequest<IBool>
{
    public uint ConstructorId => 0x1513e7b0;
    public MyTelegram.Schema.IInputPeer Peer { get; set; }
    public TVector<MyTelegram.Schema.IInputSavedStarGift> Stargift { get; set; }

    public void ComputeFlag()
    {

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Peer);
        writer.Write(Stargift);
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        Peer = reader.Read<MyTelegram.Schema.IInputPeer>();
        Stargift = reader.Read<TVector<MyTelegram.Schema.IInputSavedStarGift>>();
    }
}
