// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema.Payments;

///<summary>
/// See <a href="https://corefork.telegram.org/method/payments.getSavedStarGifts" />
///</summary>
[TlObject(0x23830de9)]
public sealed class RequestGetSavedStarGifts : IRequest<MyTelegram.Schema.Payments.ISavedStarGifts>
{
    public uint ConstructorId => 0x23830de9;
    public BitArray Flags { get; set; } = new BitArray(32);
    public bool ExcludeUnsaved { get; set; }
    public bool ExcludeSaved { get; set; }
    public bool ExcludeUnlimited { get; set; }
    public bool ExcludeLimited { get; set; }
    public bool ExcludeUnique { get; set; }
    public bool SortByValue { get; set; }
    public MyTelegram.Schema.IInputPeer Peer { get; set; }
    public string Offset { get; set; }
    public int Limit { get; set; }

    public void ComputeFlag()
    {
        if (ExcludeUnsaved) { Flags[0] = true; }
        if (ExcludeSaved) { Flags[1] = true; }
        if (ExcludeUnlimited) { Flags[2] = true; }
        if (ExcludeLimited) { Flags[3] = true; }
        if (ExcludeUnique) { Flags[4] = true; }
        if (SortByValue) { Flags[5] = true; }

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Flags);
        writer.Write(Peer);
        writer.Write(Offset);
        writer.Write(Limit);
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        Flags = reader.ReadBitArray();
        if (Flags[0]) { ExcludeUnsaved = true; }
        if (Flags[1]) { ExcludeSaved = true; }
        if (Flags[2]) { ExcludeUnlimited = true; }
        if (Flags[3]) { ExcludeLimited = true; }
        if (Flags[4]) { ExcludeUnique = true; }
        if (Flags[5]) { SortByValue = true; }
        Peer = reader.Read<MyTelegram.Schema.IInputPeer>();
        Offset = reader.ReadString();
        Limit = reader.ReadInt32();
    }
}
