// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema.Payments;

///<summary>
/// See <a href="https://corefork.telegram.org/method/payments.toggleChatStarGiftNotifications" />
///</summary>
[TlObject(0x60eaefa1)]
public sealed class RequestToggleChatStarGiftNotifications : IRequest<IBool>
{
    public uint ConstructorId => 0x60eaefa1;
    public BitArray Flags { get; set; } = new BitArray(32);
    public bool Enabled { get; set; }
    public MyTelegram.Schema.IInputPeer Peer { get; set; }

    public void ComputeFlag()
    {
        if (Enabled) { Flags[0] = true; }

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Flags);
        writer.Write(Peer);
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        Flags = reader.ReadBitArray();
        if (Flags[0]) { Enabled = true; }
        Peer = reader.Read<MyTelegram.Schema.IInputPeer>();
    }
}
