// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema.Payments;

///<summary>
/// See <a href="https://corefork.telegram.org/constructor/payments.resaleStarGifts" />
///</summary>
[TlObject(0x947a12df)]
public sealed class TResaleStarGifts : IResaleStarGifts
{
    public uint ConstructorId => 0x947a12df;
    public BitArray Flags { get; set; } = new BitArray(32);
    public int Count { get; set; }
    public TVector<MyTelegram.Schema.IStarGift> Gifts { get; set; }
    public string? NextOffset { get; set; }
    public TVector<MyTelegram.Schema.IStarGiftAttribute>? Attributes { get; set; }
    public long? AttributesHash { get; set; }
    public TVector<MyTelegram.Schema.IChat> Chats { get; set; }
    public TVector<MyTelegram.Schema.IStarGiftAttributeCounter>? Counters { get; set; }
    public TVector<MyTelegram.Schema.IUser> Users { get; set; }

    public void ComputeFlag()
    {
        if (NextOffset != null) { Flags[0] = true; }
        if (Attributes?.Count > 0) { Flags[1] = true; }
        if (/*AttributesHash != 0 &&*/ AttributesHash.HasValue) { Flags[1] = true; }
        if (Counters?.Count > 0) { Flags[2] = true; }

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Flags);
        writer.Write(Count);
        writer.Write(Gifts);
        if (Flags[0]) { writer.Write(NextOffset); }
        if (Flags[1]) { writer.Write(Attributes); }
        if (Flags[1]) { writer.Write(AttributesHash.Value); }
        writer.Write(Chats);
        if (Flags[2]) { writer.Write(Counters); }
        writer.Write(Users);
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        Flags = reader.ReadBitArray();
        Count = reader.ReadInt32();
        Gifts = reader.Read<TVector<MyTelegram.Schema.IStarGift>>();
        if (Flags[0]) { NextOffset = reader.ReadString(); }
        if (Flags[1]) { Attributes = reader.Read<TVector<MyTelegram.Schema.IStarGiftAttribute>>(); }
        if (Flags[1]) { AttributesHash = reader.ReadInt64(); }
        Chats = reader.Read<TVector<MyTelegram.Schema.IChat>>();
        if (Flags[2]) { Counters = reader.Read<TVector<MyTelegram.Schema.IStarGiftAttributeCounter>>(); }
        Users = reader.Read<TVector<MyTelegram.Schema.IUser>>();
    }
}