// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema.Payments;

///<summary>
/// See <a href="https://corefork.telegram.org/constructor/payments.savedStarGifts" />
///</summary>
[TlObject(0x95f389b1)]
public sealed class TSavedStarGifts : ISavedStarGifts
{
    public uint ConstructorId => 0x95f389b1;
    public BitArray Flags { get; set; } = new BitArray(32);
    public int Count { get; set; }
    public bool? ChatNotificationsEnabled { get; set; }
    public TVector<MyTelegram.Schema.ISavedStarGift> Gifts { get; set; }
    public string? NextOffset { get; set; }
    public TVector<MyTelegram.Schema.IChat> Chats { get; set; }
    public TVector<MyTelegram.Schema.IUser> Users { get; set; }

    public void ComputeFlag()
    {
        if (ChatNotificationsEnabled !=null) { Flags[1] = true; }
        if (NextOffset != null) { Flags[0] = true; }

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Flags);
        writer.Write(Count);
        if (Flags[1]) { writer.Write(ChatNotificationsEnabled.Value); }
        writer.Write(Gifts);
        if (Flags[0]) { writer.Write(NextOffset); }
        writer.Write(Chats);
        writer.Write(Users);
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        Flags = reader.ReadBitArray();
        Count = reader.ReadInt32();
        if (Flags[1]) { ChatNotificationsEnabled = reader.Read(); }
        Gifts = reader.Read<TVector<MyTelegram.Schema.ISavedStarGift>>();
        if (Flags[0]) { NextOffset = reader.ReadString(); }
        Chats = reader.Read<TVector<MyTelegram.Schema.IChat>>();
        Users = reader.Read<TVector<MyTelegram.Schema.IUser>>();
    }
}