// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema.Payments;

///<summary>
/// See <a href="https://corefork.telegram.org/constructor/payments.starGiftUpgradePreview" />
///</summary>
[TlObject(0x167bd90b)]
public sealed class TStarGiftUpgradePreview : IStarGiftUpgradePreview
{
    public uint ConstructorId => 0x167bd90b;
    public TVector<MyTelegram.Schema.IStarGiftAttribute> SampleAttributes { get; set; }

    public void ComputeFlag()
    {

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(SampleAttributes);
    }

    public void Deserialize(ref ReadOnlyMemory<byte> buffer)
    {
        SampleAttributes = buffer.Read<TVector<MyTelegram.Schema.IStarGiftAttribute>>();
    }
}