// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema.Payments;

///<summary>
/// See <a href="https://corefork.telegram.org/constructor/payments.uniqueStarGift" />
///</summary>
[TlObject(0xcaa2f60b)]
public sealed class TUniqueStarGift : IUniqueStarGift
{
    public uint ConstructorId => 0xcaa2f60b;
    public MyTelegram.Schema.IStarGift Gift { get; set; }
    public TVector<MyTelegram.Schema.IUser> Users { get; set; }

    public void ComputeFlag()
    {

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Gift);
        writer.Write(Users);
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        Gift = reader.Read<MyTelegram.Schema.IStarGift>();
        Users = reader.Read<TVector<MyTelegram.Schema.IUser>>();
    }
}