// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema;

///<summary>
/// See <a href="https://corefork.telegram.org/constructor/savedStarGift" />
///</summary>
[TlObject(0x6056dba5)]
public sealed class TSavedStarGift : ISavedStarGift
{
    public uint ConstructorId => 0x6056dba5;
    public BitArray Flags { get; set; } = new BitArray(32);
    public bool NameHidden { get; set; }
    public bool Unsaved { get; set; }
    public bool Refunded { get; set; }
    public bool CanUpgrade { get; set; }
    public bool PinnedToTop { get; set; }
    public MyTelegram.Schema.IPeer? FromId { get; set; }
    public int Date { get; set; }
    public MyTelegram.Schema.IStarGift Gift { get; set; }
    public MyTelegram.Schema.ITextWithEntities? Message { get; set; }
    public int? MsgId { get; set; }
    public long? SavedId { get; set; }
    public long? ConvertStars { get; set; }
    public long? UpgradeStars { get; set; }
    public int? CanExportAt { get; set; }
    public long? TransferStars { get; set; }

    public void ComputeFlag()
    {
        if (NameHidden) { Flags[0] = true; }
        if (Unsaved) { Flags[5] = true; }
        if (Refunded) { Flags[9] = true; }
        if (CanUpgrade) { Flags[10] = true; }
        if (PinnedToTop) { Flags[12] = true; }
        if (FromId != null) { Flags[1] = true; }
        if (Message != null) { Flags[2] = true; }
        if (/*MsgId != 0 && */MsgId.HasValue) { Flags[3] = true; }
        if (/*SavedId != 0 &&*/ SavedId.HasValue) { Flags[11] = true; }
        if (/*ConvertStars != 0 &&*/ ConvertStars.HasValue) { Flags[4] = true; }
        if (/*UpgradeStars != 0 &&*/ UpgradeStars.HasValue) { Flags[6] = true; }
        if (/*CanExportAt != 0 && */CanExportAt.HasValue) { Flags[7] = true; }
        if (/*TransferStars != 0 &&*/ TransferStars.HasValue) { Flags[8] = true; }
    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Flags);
        if (Flags[1]) { writer.Write(FromId); }
        writer.Write(Date);
        writer.Write(Gift);
        if (Flags[2]) { writer.Write(Message); }
        if (Flags[3]) { writer.Write(MsgId.Value); }
        if (Flags[11]) { writer.Write(SavedId.Value); }
        if (Flags[4]) { writer.Write(ConvertStars.Value); }
        if (Flags[6]) { writer.Write(UpgradeStars.Value); }
        if (Flags[7]) { writer.Write(CanExportAt.Value); }
        if (Flags[8]) { writer.Write(TransferStars.Value); }
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        Flags = reader.ReadBitArray();
        if (Flags[0]) { NameHidden = true; }
        if (Flags[5]) { Unsaved = true; }
        if (Flags[9]) { Refunded = true; }
        if (Flags[10]) { CanUpgrade = true; }
        if (Flags[12]) { PinnedToTop = true; }
        if (Flags[1]) { FromId = reader.Read<MyTelegram.Schema.IPeer>(); }
        Date = reader.ReadInt32();
        Gift = reader.Read<MyTelegram.Schema.IStarGift>();
        if (Flags[2]) { Message = reader.Read<MyTelegram.Schema.ITextWithEntities>(); }
        if (Flags[3]) { MsgId = reader.ReadInt32(); }
        if (Flags[11]) { SavedId = reader.ReadInt64(); }
        if (Flags[4]) { ConvertStars = reader.ReadInt64(); }
        if (Flags[6]) { UpgradeStars = reader.ReadInt64(); }
        if (Flags[7]) { CanExportAt = reader.ReadInt32(); }
        if (Flags[8]) { TransferStars = reader.ReadInt64(); }
    }
}