// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema;

///<summary>
/// See <a href="https://corefork.telegram.org/method/invokeWithBusinessConnection" />
///</summary>
[TlObject(0xdd289f8e)]
public sealed class RequestInvokeWithBusinessConnection : IRequest<IObject>, IHasSubQuery
{
    public uint ConstructorId => 0xdd289f8e;
    public string ConnectionId { get; set; }
    public IObject Query { get; set; }

    public void ComputeFlag()
    {

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(ConnectionId);
        writer.Write(Query);
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        ConnectionId = reader.ReadString();
        Query = reader.Read<IObject>();
    }
}
