// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema;

///<summary>
/// See <a href="https://corefork.telegram.org/constructor/inputSavedStarGiftChat" />
///</summary>
[TlObject(0xf101aa7f)]
public sealed class TInputSavedStarGiftChat : IInputSavedStarGift
{
    public uint ConstructorId => 0xf101aa7f;
    public MyTelegram.Schema.IInputPeer Peer { get; set; }
    public long SavedId { get; set; }

    public void ComputeFlag()
    {

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Peer);
        writer.Write(SavedId);
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        Peer = reader.Read<MyTelegram.Schema.IInputPeer>();
        SavedId = reader.ReadInt64();
    }
}