// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema.Account;

///<summary>
/// See <a href="https://corefork.telegram.org/method/account.getPaidMessagesRevenue" />
///</summary>
[TlObject(0xf1266f38)]
public sealed class RequestGetPaidMessagesRevenue : IRequest<MyTelegram.Schema.Account.IPaidMessagesRevenue>
{
    public uint ConstructorId => 0xf1266f38;
    public MyTelegram.Schema.IInputUser UserId { get; set; }

    public void ComputeFlag()
    {

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(UserId);
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        UserId = reader.Read<MyTelegram.Schema.IInputUser>();
    }
}
