// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema.Account;

///<summary>
/// See <a href="https://corefork.telegram.org/method/account.addNoPaidMessagesException" />
///</summary>
[TlObject(0x6f688aa7)]
public sealed class RequestAddNoPaidMessagesException : IRequest<IBool>
{
    public uint ConstructorId => 0x6f688aa7;
    public BitArray Flags { get; set; } = new BitArray(32);
    public bool RefundCharged { get; set; }
    public MyTelegram.Schema.IInputUser UserId { get; set; }

    public void ComputeFlag()
    {
        if (RefundCharged) { Flags[0] = true; }

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Flags);
        writer.Write(UserId);
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        Flags = reader.ReadBitArray();
        if (Flags[0]) { RefundCharged = true; }
        UserId = reader.Read<MyTelegram.Schema.IInputUser>();
    }
}
