// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema.Messages;

///<summary>
/// See <a href="https://corefork.telegram.org/method/messages.getSavedDialogsByID" />
///</summary>
[TlObject(0x6f6f9c96)]
public sealed class RequestGetSavedDialogsByID : IRequest<MyTelegram.Schema.Messages.ISavedDialogs>
{
    public uint ConstructorId => 0x6f6f9c96;
    public BitArray Flags { get; set; } = new BitArray(32);
    public MyTelegram.Schema.IInputPeer? ParentPeer { get; set; }
    public TVector<MyTelegram.Schema.IInputPeer> Ids { get; set; }

    public void ComputeFlag()
    {
        if (ParentPeer != null) { Flags[1] = true; }

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Flags);
        if (Flags[1]) { writer.Write(ParentPeer); }
        writer.Write(Ids);
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        Flags = reader.ReadBitArray();
        if (Flags[1]) { ParentPeer = reader.Read<MyTelegram.Schema.IInputPeer>(); }
        Ids = reader.Read<TVector<MyTelegram.Schema.IInputPeer>>();
    }
}
