// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema.Messages;

///<summary>
/// See <a href="https://corefork.telegram.org/method/messages.reportMessagesDelivery" />
///</summary>
[TlObject(0x5a6d7395)]
public sealed class RequestReportMessagesDelivery : IRequest<IBool>
{
    public uint ConstructorId => 0x5a6d7395;
    public BitArray Flags { get; set; } = new BitArray(32);
    public bool Push { get; set; }
    public MyTelegram.Schema.IInputPeer Peer { get; set; }
    public TVector<int> Id { get; set; }

    public void ComputeFlag()
    {
        if (Push) { Flags[0] = true; }

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Flags);
        writer.Write(Peer);
        writer.Write(Id);
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        Flags = reader.ReadBitArray();
        if (Flags[0]) { Push = true; }
        Peer = reader.Read<MyTelegram.Schema.IInputPeer>();
        Id = reader.Read<TVector<int>>();
    }
}
