// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema;

///<summary>
/// See <a href="https://corefork.telegram.org/constructor/inputStorePaymentAuthCode" />
///</summary>
[TlObject(0x9bb2636d)]
public sealed class TInputStorePaymentAuthCode : IInputStorePaymentPurpose
{
    public uint ConstructorId => 0x9bb2636d;
    public BitArray Flags { get; set; } = new BitArray(32);
    public bool Restore { get; set; }
    public string PhoneNumber { get; set; }
    public string PhoneCodeHash { get; set; }
    public string Currency { get; set; }
    public long Amount { get; set; }

    public void ComputeFlag()
    {
        if (Restore) { Flags[0] = true; }

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Flags);
        writer.Write(PhoneNumber);
        writer.Write(PhoneCodeHash);
        writer.Write(Currency);
        writer.Write(Amount);
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        Flags = reader.ReadBitArray();
        if (Flags[0]) { Restore = true; }
        PhoneNumber = reader.ReadString();
        PhoneCodeHash = reader.ReadString();
        Currency = reader.ReadString();
        Amount = reader.ReadInt64();
    }
}