// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema.Bots;

///<summary>
/// See <a href="https://corefork.telegram.org/method/bots.setCustomVerification" />
///</summary>
[TlObject(0x8b89dfbd)]
public sealed class RequestSetCustomVerification : IRequest<IBool>
{
    public uint ConstructorId => 0x8b89dfbd;
    public BitArray Flags { get; set; } = new BitArray(32);
    public bool Enabled { get; set; }
    public MyTelegram.Schema.IInputUser? Bot { get; set; }
    public MyTelegram.Schema.IInputPeer Peer { get; set; }
    public string? CustomDescription { get; set; }

    public void ComputeFlag()
    {
        if (Enabled) { Flags[1] = true; }
        if (Bot != null) { Flags[0] = true; }
        if (CustomDescription != null) { Flags[2] = true; }
    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Flags);
        if (Flags[0]) { writer.Write(Bot); }
        writer.Write(Peer);
        if (Flags[2]) { writer.Write(CustomDescription); }
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        Flags = reader.ReadBitArray();
        if (Flags[1]) { Enabled = true; }
        if (Flags[0]) { Bot = reader.Read<MyTelegram.Schema.IInputUser>(); }
        Peer = reader.Read<MyTelegram.Schema.IInputPeer>();
        if (Flags[2]) { CustomDescription = reader.ReadString(); }
    }
}
