// <auto-generated />

using MyTelegram.Messenger.Services;

namespace MyTelegram.Messenger.Handlers.LatestLayer.Payments;

/// <summary>
/// See <a href="https://corefork.telegram.org/method/payments.createStarGiftCollection" />
/// </summary>
internal sealed class CreateStarGiftCollectionHandler : RpcResultObjectHandler<MyTelegram.Schema.Payments.RequestCreateStarGiftCollection, MyTelegram.Schema.IStarGiftCollection>, IObjectHandler
{
	private readonly ISavedStarGiftsService _savedService;

	public CreateStarGiftCollectionHandler(ISavedStarGiftsService savedService)
	{
		_savedService = savedService;
	}

	protected override Task<MyTelegram.Schema.IStarGiftCollection> HandleCoreAsync(IRequestInput input, MyTelegram.Schema.Payments.RequestCreateStarGiftCollection obj)
	{
		return _savedService.CreateCollectionAsync(input.UserId, obj.Title, obj.Stargift);
	}
}

