// <auto-generated />

using MyTelegram.Messenger.Services;

namespace MyTelegram.Messenger.Handlers.LatestLayer.Payments;

/// <summary>
/// See <a href="https://corefork.telegram.org/method/payments.deleteStarGiftCollection" />
/// </summary>
internal sealed class DeleteStarGiftCollectionHandler : RpcResultObjectHandler<MyTelegram.Schema.Payments.RequestDeleteStarGiftCollection, IBool>, IObjectHandler
{
	private readonly ISavedStarGiftsService _savedService;

	public DeleteStarGiftCollectionHandler(ISavedStarGiftsService savedService)
	{
		_savedService = savedService;
	}

	protected override async Task<IBool> HandleCoreAsync(IRequestInput input, MyTelegram.Schema.Payments.RequestDeleteStarGiftCollection obj)
	{
		var ok = await _savedService.DeleteCollectionAsync(input.UserId, obj.Slug);
		return ok ? new TBoolTrue() : new TBoolFalse();
	}
}

