// <auto-generated />

using MyTelegram.Messenger.Services;
using MyTelegram.Schema.Payments;

namespace MyTelegram.Messenger.Handlers.LatestLayer.Payments;

///<summary>
/// See <a href="https://corefork.telegram.org/method/payments.getStarGiftCollections" />
///</summary>
internal sealed class GetStarGiftCollectionsHandler(ISavedStarGiftsService savedService) : RpcResultObjectHandler<MyTelegram.Schema.Payments.RequestGetStarGiftCollections, MyTelegram.Schema.Payments.IStarGiftCollections>, IObjectHandler
{
    protected override Task<MyTelegram.Schema.Payments.IStarGiftCollections> HandleCoreAsync(IRequestInput input, MyTelegram.Schema.Payments.RequestGetStarGiftCollections obj)
    {
        return savedService.GetCollectionsAsync(input.UserId);
    }
}

