// <auto-generated />

using MyTelegram.Messenger.Services;

namespace MyTelegram.Messenger.Handlers.LatestLayer.Payments;

/// <summary>
/// See <a href="https://corefork.telegram.org/method/payments.reorderStarGiftCollections" />
/// </summary>
internal sealed class ReorderStarGiftCollectionsHandler : RpcResultObjectHandler<MyTelegram.Schema.Payments.RequestReorderStarGiftCollections, IBool>, IObjectHandler
{
	private readonly ISavedStarGiftsService _savedService;

	public ReorderStarGiftCollectionsHandler(ISavedStarGiftsService savedService)
	{
		_savedService = savedService;
	}

	protected override async Task<IBool> HandleCoreAsync(IRequestInput input, MyTelegram.Schema.Payments.RequestReorderStarGiftCollections obj)
	{
		await _savedService.ReorderCollectionsAsync(input.UserId, obj.Order);
		return new TBoolTrue();
	}
}

