// <auto-generated />

using MyTelegram.Messenger.Services;

namespace MyTelegram.Messenger.Handlers.LatestLayer.Payments;

///<summary>
/// See <a href="https://corefork.telegram.org/method/payments.updateStarGiftCollection" />
///</summary>
internal sealed class UpdateStarGiftCollectionHandler(ISavedStarGiftsService savedService) : RpcResultObjectHandler<MyTelegram.Schema.Payments.RequestUpdateStarGiftCollection, MyTelegram.Schema.IStarGiftCollection>, IObjectHandler
{
    protected override Task<MyTelegram.Schema.IStarGiftCollection> HandleCoreAsync(IRequestInput input, MyTelegram.Schema.Payments.RequestUpdateStarGiftCollection obj)
    {
        return savedService.UpdateCollectionAsync(input.UserId,
            obj.Slug,
            obj.Title,
            obj.DeleteStargift,
            obj.AddStargift,
            obj.Order);
    }
}

