// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema;

///<summary>
/// See <a href="https://corefork.telegram.org/constructor/emojiStatusCollectible" />
///</summary>
[TlObject(0x7184603b)]
public sealed class TEmojiStatusCollectible : IEmojiStatus
{
    public uint ConstructorId => 0x7184603b;
    public BitArray Flags { get; set; } = new BitArray(32);
    public long CollectibleId { get; set; }
    public long DocumentId { get; set; }
    public string Title { get; set; }
    public string Slug { get; set; }
    public long PatternDocumentId { get; set; }
    public int CenterColor { get; set; }
    public int EdgeColor { get; set; }
    public int PatternColor { get; set; }
    public int TextColor { get; set; }
    public int? Until { get; set; }

    public void ComputeFlag()
    {
        if (/*Until != 0 && */Until.HasValue) { Flags[0] = true; }
    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Flags);
        writer.Write(CollectibleId);
        writer.Write(DocumentId);
        writer.Write(Title);
        writer.Write(Slug);
        writer.Write(PatternDocumentId);
        writer.Write(CenterColor);
        writer.Write(EdgeColor);
        writer.Write(PatternColor);
        writer.Write(TextColor);
        if (Flags[0]) { writer.Write(Until.Value); }
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        Flags = reader.ReadBitArray();
        CollectibleId = reader.ReadInt64();
        DocumentId = reader.ReadInt64();
        Title = reader.ReadString();
        Slug = reader.ReadString();
        PatternDocumentId = reader.ReadInt64();
        CenterColor = reader.ReadInt32();
        EdgeColor = reader.ReadInt32();
        PatternColor = reader.ReadInt32();
        TextColor = reader.ReadInt32();
        if (Flags[0]) { Until = reader.ReadInt32(); }
    }
}