// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema;

///<summary>
/// See <a href="https://corefork.telegram.org/constructor/inputEmojiStatusCollectible" />
///</summary>
[TlObject(0x7141dbf)]
public sealed class TInputEmojiStatusCollectible : IEmojiStatus
{
    public uint ConstructorId => 0x7141dbf;
    public BitArray Flags { get; set; } = new BitArray(32);
    public long CollectibleId { get; set; }
    public int? Until { get; set; }

    public void ComputeFlag()
    {
        if (/*Until != 0 && */Until.HasValue) { Flags[0] = true; }
    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Flags);
        writer.Write(CollectibleId);
        if (Flags[0]) { writer.Write(Until.Value); }
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        Flags = reader.ReadBitArray();
        CollectibleId = reader.ReadInt64();
        if (Flags[0]) { Until = reader.ReadInt32(); }
    }
}