// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema.Auth;

///<summary>
/// Request an SMS code via Firebase.
/// <para>Possible errors</para>
/// Code Type Description
/// 400 PHONE_CODE_EMPTY phone_code is missing.
/// 400 PHONE_NUMBER_INVALID The phone number is invalid.
/// See <a href="https://corefork.telegram.org/method/auth.requestFirebaseSms" />
///</summary>
[TlObject(0x8e39261e)]
public sealed class RequestRequestFirebaseSms : IRequest<IBool>
{
    public uint ConstructorId => 0x8e39261e;
    ///<summary>
    /// Flags, see <a href="https://corefork.telegram.org/mtproto/TL-combinators#conditional-fields">TL conditional fields</a>
    ///</summary>
    public BitArray Flags { get; set; } = new BitArray(32);

    ///<summary>
    /// Phone number
    ///</summary>
    public string PhoneNumber { get; set; }

    ///<summary>
    /// Phone code hash returned by <a href="https://corefork.telegram.org/method/auth.sendCode">auth.sendCode</a>
    ///</summary>
    public string PhoneCodeHash { get; set; }

    ///<summary>
    /// On Android, a JWS object obtained as described in the <a href="https://corefork.telegram.org/api/auth">auth documentation »</a>
    ///</summary>
    public string? SafetyNetToken { get; set; }

    ///<summary>
    /// On Android, an object obtained as described in the <a href="https://corefork.telegram.org/api/auth">auth documentation »</a>
    ///</summary>
    public string? PlayIntegrityToken { get; set; }

    ///<summary>
    /// Secret token received via an apple push notification
    ///</summary>
    public string? IosPushSecret { get; set; }

    public void ComputeFlag()
    {
        if (SafetyNetToken != null) { Flags[0] = true; }
        if (PlayIntegrityToken != null) { Flags[2] = true; }
        if (IosPushSecret != null) { Flags[1] = true; }
    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Flags);
        writer.Write(PhoneNumber);
        writer.Write(PhoneCodeHash);
        if (Flags[0]) { writer.Write(SafetyNetToken); }
        if (Flags[2]) { writer.Write(PlayIntegrityToken); }
        if (Flags[1]) { writer.Write(IosPushSecret); }
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        Flags = reader.ReadBitArray();
        PhoneNumber = reader.ReadString();
        PhoneCodeHash = reader.ReadString();
        if (Flags[0]) { SafetyNetToken = reader.ReadString(); }
        if (Flags[2]) { PlayIntegrityToken = reader.ReadString(); }
        if (Flags[1]) { IosPushSecret = reader.ReadString(); }
    }
}
