// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema;

///<summary>
/// See <a href="https://corefork.telegram.org/constructor/messageActionConferenceCall" />
///</summary>
[TlObject(0x2ffe2f7a)]
public sealed class TMessageActionConferenceCall : IMessageAction
{
    public uint ConstructorId => 0x2ffe2f7a;
    public BitArray Flags { get; set; } = new BitArray(32);
    public bool Missed { get; set; }
    public bool Active { get; set; }
    public bool Video { get; set; }
    public long CallId { get; set; }
    public int? Duration { get; set; }
    public TVector<MyTelegram.Schema.IPeer>? OtherParticipants { get; set; }

    public void ComputeFlag()
    {
        if (Missed) { Flags[0] = true; }
        if (Active) { Flags[1] = true; }
        if (Video) { Flags[4] = true; }
        if (/*Duration != 0 && */Duration.HasValue) { Flags[2] = true; }
        if (OtherParticipants?.Count > 0) { Flags[3] = true; }
    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Flags);
        writer.Write(CallId);
        if (Flags[2]) { writer.Write(Duration.Value); }
        if (Flags[3]) { writer.Write(OtherParticipants); }
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        Flags = reader.ReadBitArray();
        if (Flags[0]) { Missed = true; }
        if (Flags[1]) { Active = true; }
        if (Flags[4]) { Video = true; }
        CallId = reader.ReadInt64();
        if (Flags[2]) { Duration = reader.ReadInt32(); }
        if (Flags[3]) { OtherParticipants = reader.Read<TVector<MyTelegram.Schema.IPeer>>(); }
    }
}