// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema;

///<summary>
/// See <a href="https://corefork.telegram.org/constructor/messageActionStarGiftUnique" />
///</summary>
[TlObject(0x2e3ae60e)]
public sealed class TMessageActionStarGiftUnique : IMessageAction
{
    public uint ConstructorId => 0x2e3ae60e;
    public BitArray Flags { get; set; } = new BitArray(32);
    public bool Upgrade { get; set; }
    public bool Transferred { get; set; }
    public bool Saved { get; set; }
    public bool Refunded { get; set; }
    public MyTelegram.Schema.IStarGift Gift { get; set; }
    public int? CanExportAt { get; set; }
    public long? TransferStars { get; set; }
    public MyTelegram.Schema.IPeer? FromId { get; set; }
    public MyTelegram.Schema.IPeer? Peer { get; set; }
    public long? SavedId { get; set; }
    public long? ResaleStars { get; set; }
    public int? CanTransferAt { get; set; }
    public int? CanResellAt { get; set; }

    public void ComputeFlag()
    {
        if (Upgrade) { Flags[0] = true; }
        if (Transferred) { Flags[1] = true; }
        if (Saved) { Flags[2] = true; }
        if (Refunded) { Flags[5] = true; }
        if (/*CanExportAt != 0 && */CanExportAt.HasValue) { Flags[3] = true; }
        if (/*TransferStars != 0 &&*/ TransferStars.HasValue) { Flags[4] = true; }
        if (FromId != null) { Flags[6] = true; }
        if (Peer != null) { Flags[7] = true; }
        if (/*SavedId != 0 &&*/ SavedId.HasValue) { Flags[7] = true; }
        if (/*ResaleStars != 0 &&*/ ResaleStars.HasValue) { Flags[8] = true; }
        if (/*CanTransferAt != 0 && */CanTransferAt.HasValue) { Flags[9] = true; }
        if (/*CanResellAt != 0 && */CanResellAt.HasValue) { Flags[10] = true; }
    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Flags);
        writer.Write(Gift);
        if (Flags[3]) { writer.Write(CanExportAt.Value); }
        if (Flags[4]) { writer.Write(TransferStars.Value); }
        if (Flags[6]) { writer.Write(FromId); }
        if (Flags[7]) { writer.Write(Peer); }
        if (Flags[7]) { writer.Write(SavedId.Value); }
        if (Flags[8]) { writer.Write(ResaleStars.Value); }
        if (Flags[9]) { writer.Write(CanTransferAt.Value); }
        if (Flags[10]) { writer.Write(CanResellAt.Value); }
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        Flags = reader.ReadBitArray();
        if (Flags[0]) { Upgrade = true; }
        if (Flags[1]) { Transferred = true; }
        if (Flags[2]) { Saved = true; }
        if (Flags[5]) { Refunded = true; }
        Gift = reader.Read<MyTelegram.Schema.IStarGift>();
        if (Flags[3]) { CanExportAt = reader.ReadInt32(); }
        if (Flags[4]) { TransferStars = reader.ReadInt64(); }
        if (Flags[6]) { FromId = reader.Read<MyTelegram.Schema.IPeer>(); }
        if (Flags[7]) { Peer = reader.Read<MyTelegram.Schema.IPeer>(); }
        if (Flags[7]) { SavedId = reader.ReadInt64(); }
        if (Flags[8]) { ResaleStars = reader.ReadInt64(); }
        if (Flags[9]) { CanTransferAt = reader.ReadInt32(); }
        if (Flags[10]) { CanResellAt = reader.ReadInt32(); }
    }
}