// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema;

///<summary>
/// See <a href="https://corefork.telegram.org/constructor/messageActionPaidMessagesPrice" />
///</summary>
[TlObject(0xbcd71419)]
public sealed class TMessageActionPaidMessagesPrice : IMessageAction
{
    public uint ConstructorId => 0xbcd71419;
    public long Stars { get; set; }

    public void ComputeFlag()
    {

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Stars);
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        Stars = reader.ReadInt64();
    }
}