// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema;

///<summary>
/// See <a href="https://corefork.telegram.org/constructor/sponsoredPeer" />
///</summary>
[TlObject(0xc69708d3)]
public sealed class TSponsoredPeer : ISponsoredPeer
{
    public uint ConstructorId => 0xc69708d3;
    public BitArray Flags { get; set; } = new BitArray(32);
    public byte[] RandomId { get; set; }
    public MyTelegram.Schema.IPeer Peer { get; set; }
    public string? SponsorInfo { get; set; }
    public string? AdditionalInfo { get; set; }

    public void ComputeFlag()
    {
        if (SponsorInfo != null) { Flags[0] = true; }
        if (AdditionalInfo != null) { Flags[1] = true; }
    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Flags);
        writer.Write(RandomId);
        writer.Write(Peer);
        if (Flags[0]) { writer.Write(SponsorInfo); }
        if (Flags[1]) { writer.Write(AdditionalInfo); }
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        Flags = reader.ReadBitArray();
        RandomId = reader.ReadBytes();
        Peer = reader.Read<MyTelegram.Schema.IPeer>();
        if (Flags[0]) { SponsorInfo = reader.ReadString(); }
        if (Flags[1]) { AdditionalInfo = reader.ReadString(); }
    }
}