// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema.Users;

///<summary>
/// See <a href="https://corefork.telegram.org/method/users.getRequirementsToContact" />
///</summary>
[TlObject(0xd89a83a3)]
public sealed class RequestGetRequirementsToContact : IRequest<TVector<MyTelegram.Schema.IRequirementToContact>>
{
    public uint ConstructorId => 0xd89a83a3;
    public TVector<MyTelegram.Schema.IInputUser> Id { get; set; }

    public void ComputeFlag()
    {

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Id);
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        Id = reader.Read<TVector<MyTelegram.Schema.IInputUser>>();
    }
}
