// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema.Phone;

///<summary>
/// See <a href="https://corefork.telegram.org/method/phone.deleteConferenceCallParticipants" />
///</summary>
[TlObject(0x8ca60525)]
public sealed class RequestDeleteConferenceCallParticipants : IRequest<MyTelegram.Schema.IUpdates>
{
    public uint ConstructorId => 0x8ca60525;
    public BitArray Flags { get; set; } = new BitArray(32);
    public bool OnlyLeft { get; set; }
    public bool Kick { get; set; }
    public MyTelegram.Schema.IInputGroupCall Call { get; set; }
    public TVector<long> Ids { get; set; }
    public byte[] Block { get; set; }

    public void ComputeFlag()
    {
        if (OnlyLeft) { Flags[0] = true; }
        if (Kick) { Flags[1] = true; }

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Flags);
        writer.Write(Call);
        writer.Write(Ids);
        writer.Write(Block);
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        Flags = reader.ReadBitArray();
        if (Flags[0]) { OnlyLeft = true; }
        if (Flags[1]) { Kick = true; }
        Call = reader.Read<MyTelegram.Schema.IInputGroupCall>();
        Ids = reader.Read<TVector<long>>();
        Block = reader.ReadBytes();
    }
}
