// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema.Phone;

///<summary>
/// See <a href="https://corefork.telegram.org/method/phone.createConferenceCall" />
///</summary>
[TlObject(0xdfc909ab)]
public sealed class RequestCreateConferenceCall : IRequest<MyTelegram.Schema.Phone.IPhoneCall>
{
    public uint ConstructorId => 0xdfc909ab;
    public MyTelegram.Schema.IInputPhoneCall Peer { get; set; }
    public long KeyFingerprint { get; set; }

    public void ComputeFlag()
    {

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Peer);
        writer.Write(KeyFingerprint);
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        Peer = reader.Read<MyTelegram.Schema.IInputPhoneCall>();
        KeyFingerprint = reader.ReadInt64();
    }
}
