// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema.Phone;

///<summary>
/// See <a href="https://corefork.telegram.org/method/phone.inviteConferenceCallParticipant" />
///</summary>
[TlObject(0xbcf22685)]
public sealed class RequestInviteConferenceCallParticipant : IRequest<MyTelegram.Schema.IUpdates>
{
    public uint ConstructorId => 0xbcf22685;
    public BitArray Flags { get; set; } = new BitArray(32);
    public bool Video { get; set; }
    public MyTelegram.Schema.IInputGroupCall Call { get; set; }
    public MyTelegram.Schema.IInputUser UserId { get; set; }

    public void ComputeFlag()
    {
        if (Video) { Flags[0] = true; }

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Flags);
        writer.Write(Call);
        writer.Write(UserId);
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        Flags = reader.ReadBitArray();
        if (Flags[0]) { Video = true; }
        Call = reader.Read<MyTelegram.Schema.IInputGroupCall>();
        UserId = reader.Read<MyTelegram.Schema.IInputUser>();
    }
}
