// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema.Phone;

///<summary>
/// See <a href="https://corefork.telegram.org/method/phone.getGroupCallChainBlocks" />
///</summary>
[TlObject(0xee9f88a6)]
public sealed class RequestGetGroupCallChainBlocks : IRequest<MyTelegram.Schema.IUpdates>
{
    public uint ConstructorId => 0xee9f88a6;
    public MyTelegram.Schema.IInputGroupCall Call { get; set; }
    public int SubChainId { get; set; }
    public int Offset { get; set; }
    public int Limit { get; set; }

    public void ComputeFlag()
    {

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Call);
        writer.Write(SubChainId);
        writer.Write(Offset);
        writer.Write(Limit);
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        Call = reader.Read<MyTelegram.Schema.IInputGroupCall>();
        SubChainId = reader.ReadInt32();
        Offset = reader.ReadInt32();
        Limit = reader.ReadInt32();
    }
}
