// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema;

///<summary>
/// See <a href="https://corefork.telegram.org/constructor/businessBotRights" />
///</summary>
[TlObject(0xa0624cf7)]
public sealed class TBusinessBotRights : IBusinessBotRights
{
    public uint ConstructorId => 0xa0624cf7;
    public BitArray Flags { get; set; } = new BitArray(32);
    public bool Reply { get; set; }
    public bool ReadMessages { get; set; }
    public bool DeleteSentMessages { get; set; }
    public bool DeleteReceivedMessages { get; set; }
    public bool EditName { get; set; }
    public bool EditBio { get; set; }
    public bool EditProfilePhoto { get; set; }
    public bool EditUsername { get; set; }
    public bool ViewGifts { get; set; }
    public bool SellGifts { get; set; }
    public bool ChangeGiftSettings { get; set; }
    public bool TransferAndUpgradeGifts { get; set; }
    public bool TransferStars { get; set; }
    public bool ManageStories { get; set; }

    public void ComputeFlag()
    {
        if (Reply) { Flags[0] = true; }
        if (ReadMessages) { Flags[1] = true; }
        if (DeleteSentMessages) { Flags[2] = true; }
        if (DeleteReceivedMessages) { Flags[3] = true; }
        if (EditName) { Flags[4] = true; }
        if (EditBio) { Flags[5] = true; }
        if (EditProfilePhoto) { Flags[6] = true; }
        if (EditUsername) { Flags[7] = true; }
        if (ViewGifts) { Flags[8] = true; }
        if (SellGifts) { Flags[9] = true; }
        if (ChangeGiftSettings) { Flags[10] = true; }
        if (TransferAndUpgradeGifts) { Flags[11] = true; }
        if (TransferStars) { Flags[12] = true; }
        if (ManageStories) { Flags[13] = true; }
    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Flags);

    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        Flags = reader.ReadBitArray();
        if (Flags[0]) { Reply = true; }
        if (Flags[1]) { ReadMessages = true; }
        if (Flags[2]) { DeleteSentMessages = true; }
        if (Flags[3]) { DeleteReceivedMessages = true; }
        if (Flags[4]) { EditName = true; }
        if (Flags[5]) { EditBio = true; }
        if (Flags[6]) { EditProfilePhoto = true; }
        if (Flags[7]) { EditUsername = true; }
        if (Flags[8]) { ViewGifts = true; }
        if (Flags[9]) { SellGifts = true; }
        if (Flags[10]) { ChangeGiftSettings = true; }
        if (Flags[11]) { TransferAndUpgradeGifts = true; }
        if (Flags[12]) { TransferStars = true; }
        if (Flags[13]) { ManageStories = true; }
    }
}