// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema.E2e;


[TlObject(0x639a3db6)]
public sealed class TBlock : IBlock
{
    public uint ConstructorId => 0x639a3db6;
    public byte[] Signature { get; set; }
    public BitArray Flags { get; set; } = new BitArray(32);
    public byte[] PrevBlockHash { get; set; }
    public TVector<MyTelegram.Schema.E2e.IChange> Changes { get; set; }
    public int Height { get; set; }
    public MyTelegram.Schema.E2e.IStateProof StateProof { get; set; }
    public byte[]? SignaturePublicKey { get; set; }

    public void ComputeFlag()
    {
        if (SignaturePublicKey != null) { Flags[0] = true; }
    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.WriteRawBytes(Signature);
        writer.Write(Flags);
        writer.WriteRawBytes(PrevBlockHash);
        writer.WriteVector(Changes);
        writer.Write(Height);
        writer.Write(StateProof);
        if (Flags[0]) { writer.WriteRawBytes(SignaturePublicKey); }
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        Signature = reader.ReadInt512();
        Flags = reader.ReadBitArray();
        PrevBlockHash = reader.ReadInt256();
        Changes = reader.ReadVector<MyTelegram.Schema.E2e.IChange>();
        Height = reader.ReadInt32();
        StateProof = reader.Read<MyTelegram.Schema.E2e.IStateProof>();
        if (Flags[0]) { SignaturePublicKey = reader.ReadInt256(); }
    }
}