// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema.E2e;


[TlObject(0x987A2158)]
public sealed class TChangeSetSharedKey : IChange
{
    public uint ConstructorId => 0x987A2158;
    public MyTelegram.Schema.E2e.ISharedKey SharedKey { get; set; }

    public void ComputeFlag()
    {

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(SharedKey);
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        SharedKey = reader.Read<MyTelegram.Schema.E2e.ISharedKey>();
    }
}