// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema.E2e;


[TlObject(0xFE0139CC)]
public sealed class TChangeSetValue : IChange
{
    public uint ConstructorId => 0xFE0139CC;
    public byte[] Key { get; set; }
    public byte[] Value { get; set; }

    public void ComputeFlag()
    {

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Key);
        writer.Write(Value);
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        Key = reader.ReadBytes();
        Value = reader.ReadBytes();
    }
}