// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema.E2e;


[TlObject(0x83f4f9d8)]
public sealed class TGroupBroadcastNonceReveal : IGroupBroadcast
{
    public uint ConstructorId => 0x83f4f9d8;
    public byte[] Signature { get; set; }
    public long UserId { get; set; }
    public int ChainHeight { get; set; }
    public byte[] ChainHash { get; set; }
    public byte[] Nonce { get; set; }

    public void ComputeFlag()
    {

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Signature);
        writer.Write(UserId);
        writer.Write(ChainHeight);
        writer.WriteRawBytes(ChainHash);
        writer.WriteRawBytes(Nonce);
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        Signature = reader.ReadBytes();
        UserId = reader.ReadInt64();
        ChainHeight = reader.ReadInt32();
        ChainHash = reader.ReadInt256();
        Nonce = reader.ReadInt256();
    }
}