// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema.E2e;


[TlObject(0xd1512ae7)]
public sealed class TGroupBroadcastNonceCommit : IGroupBroadcast
{
    public uint ConstructorId => 0xd1512ae7;
    public byte[] Signature { get; set; }
    public long UserId { get; set; }
    public int ChainHeight { get; set; }
    public byte[] ChainHash { get; set; }
    public byte[] NonceHash { get; set; }

    public void ComputeFlag()
    {

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.WriteRawBytes(Signature);
        writer.Write(UserId);
        writer.Write(ChainHeight);
        writer.WriteRawBytes(ChainHash);
        writer.WriteRawBytes(NonceHash);
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        Signature = reader.ReadInt512();
        UserId = reader.ReadInt64();
        ChainHeight = reader.ReadInt32();
        ChainHash = reader.ReadInt256();
        NonceHash = reader.ReadInt256();
    }
}