// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema.E2e;


[TlObject(0x18F3971F)]
public sealed class TGroupParticipant : IGroupParticipant
{
    public uint ConstructorId => 0x18F3971F;
    public long UserId { get; set; }
    public byte[] PublicKey { get; set; }
    public BitArray Flags { get; set; } = new BitArray(32);
    public bool AddUsers { get; set; }
    public bool RemoveUsers { get; set; }
    public int Version { get; set; }

    public void ComputeFlag()
    {
        if (AddUsers) { Flags[0] = true; }
        if (RemoveUsers) { Flags[1] = true; }

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(UserId);
        writer.WriteRawBytes(PublicKey);
        writer.Write(Flags);
        writer.Write(Version);
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        UserId = reader.ReadInt64();
        PublicKey = reader.ReadInt256();
        Flags = reader.ReadBitArray();
        if (Flags[0]) { AddUsers = true; }
        if (Flags[1]) { RemoveUsers = true; }
        Version = reader.ReadInt32();
    }
}