// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema.E2e;


[TlObject(0xD37DA15A)]
public sealed class THandshakeQR : IHandshakePublic
{
    public uint ConstructorId => 0xD37DA15A;
    public byte[] BobEphemeralPK { get; set; }
    public byte[] BobNonce { get; set; }

    public void ComputeFlag()
    {

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.WriteRawBytes(BobEphemeralPK);
        writer.WriteRawBytes(BobNonce);
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        BobEphemeralPK = reader.ReadInt256();
        BobNonce = reader.ReadInt256();
    }
}