// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema.E2e;


[TlObject(0xF6F07754)]
public sealed class THandshakeLoginExport : IHandshakePublic
{
    public uint ConstructorId => 0xF6F07754;
    public byte[] Accept { get; set; }
    public byte[] EncryptedKey { get; set; }

    public void ComputeFlag()
    {

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Accept);
        writer.Write(EncryptedKey);
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        Accept = reader.ReadBytes();
        EncryptedKey = reader.ReadBytes();
    }
}