// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema.E2e;


[TlObject(0x85FE42B7)]
public sealed class TPersonalEmojiNonces : IPersonal
{
    public uint ConstructorId => 0x85FE42B7;
    public BitArray Flags { get; set; } = new BitArray(32);
    public byte[]? SelfNonce { get; set; }
    public byte[]? ContactNonceHash { get; set; }
    public byte[]? ContactNonce { get; set; }

    public void ComputeFlag()
    {
        if (SelfNonce != null) { Flags[0] = true; }
        if (ContactNonceHash != null) { Flags[1] = true; }
        if (ContactNonce != null) { Flags[2] = true; }
    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Flags);
        if (Flags[0]) { writer.WriteRawBytes(SelfNonce); }
        if (Flags[1]) { writer.WriteRawBytes(ContactNonceHash); }
        if (Flags[2]) { writer.WriteRawBytes(ContactNonce); }
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        Flags = reader.ReadBitArray();
        if (Flags[0]) { SelfNonce = reader.ReadInt256(); }
        if (Flags[1]) { ContactNonceHash = reader.ReadInt256(); }
        if (Flags[2]) { ContactNonce = reader.ReadInt256(); }
    }
}