// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema.E2e;


[TlObject(0x3DDB7846)]
public sealed class TPersonalData : IPersonalData
{
    public uint ConstructorId => 0x3DDB7846;
    public byte[] PublicKey { get; set; }
    public TVector<MyTelegram.Schema.E2e.IPersonalOnServer> Data { get; set; }

    public void ComputeFlag()
    {

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.WriteRawBytes(PublicKey);
        writer.WriteVector(Data);
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        PublicKey = reader.ReadInt256();
        Data = reader.ReadVector<MyTelegram.Schema.E2e.IPersonalOnServer>();
    }
}