// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema.E2e;


[TlObject(0xC14AC456)]
public sealed class TPersonalContactState : IPersonal
{
    public uint ConstructorId => 0xC14AC456;
    public BitArray Flags { get; set; } = new BitArray(32);
    public bool IsContact { get; set; }

    public void ComputeFlag()
    {
        if (IsContact) { Flags[0] = true; }
    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Flags);

    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        Flags = reader.ReadBitArray();
        if (Flags[0]) { IsContact = true; }
    }
}