// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema.E2e;


[TlObject(0xEBA65211)]
public sealed class TPersonalOnClient : IPersonalOnClient
{
    public uint ConstructorId => 0xEBA65211;
    public int SignedAt { get; set; }
    public MyTelegram.Schema.E2e.IPersonal Personal { get; set; }

    public void ComputeFlag()
    {

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(SignedAt);
        writer.Write(Personal);
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        SignedAt = reader.ReadInt32();
        Personal = reader.Read<MyTelegram.Schema.E2e.IPersonal>();
    }
}