// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema.E2e;


[TlObject(0x3DDB7846)]
public sealed class TPersonalOnServer : IPersonalOnServer
{
    public uint ConstructorId => 0x3DDB7846;
    public byte[] Signature { get; set; }
    public int SignedAt { get; set; }
    public MyTelegram.Schema.E2e.IPersonal Personal { get; set; }

    public void ComputeFlag()
    {

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.WriteRawBytes(Signature);
        writer.Write(SignedAt);
        writer.Write(Personal);
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        Signature = reader.ReadInt512();
        SignedAt = reader.ReadInt32();
        Personal = reader.Read<MyTelegram.Schema.E2e.IPersonal>();
    }
}