// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema.E2e;


[TlObject(0x8A847E7F)]
public sealed class TSharedKey : ISharedKey
{
    public uint ConstructorId => 0x8A847E7F;
    public byte[] Ek { get; set; }
    public string EncryptedSharedKey { get; set; }
    public TVector<long> DestUserId { get; set; }
    public TVector<byte[]> DestHeader { get; set; }

    public void ComputeFlag()
    {

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.WriteRawBytes(Ek);
        writer.Write(EncryptedSharedKey);
        writer.Write(DestUserId);
        writer.Write(DestHeader);
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        Ek = reader.ReadInt256();
        EncryptedSharedKey = reader.ReadString();
        DestUserId = reader.Read<TVector<long>>();
        DestHeader = reader.Read<TVector<byte[]>>();
    }
}