// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema.E2e;


[TlObject(0xD6B679E6)]
public sealed class TStateProof : IStateProof
{
    public uint ConstructorId => 0xD6B679E6;
    public BitArray Flags { get; set; } = new BitArray(32);
    public byte[] KvHash { get; set; }
    public MyTelegram.Schema.E2e.IGroupState? GroupState { get; set; }
    public MyTelegram.Schema.E2e.ISharedKey? SharedKey { get; set; }

    public void ComputeFlag()
    {
        if (GroupState != null) { Flags[0] = true; }
        if (SharedKey != null) { Flags[1] = true; }
    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Flags);
        writer.WriteRawBytes(KvHash);
        if (Flags[0]) { writer.Write(GroupState); }
        if (Flags[1]) { writer.Write(SharedKey); }
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        Flags = reader.ReadBitArray();
        KvHash = reader.ReadInt256();
        if (Flags[0]) { GroupState = reader.Read<MyTelegram.Schema.E2e.IGroupState>(); }
        if (Flags[1]) { SharedKey = reader.Read<MyTelegram.Schema.E2e.ISharedKey>(); }
    }
}