// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema.E2e;


[TlObject(0xAB73BAE1)]
public sealed class TValueContactByPublicKey : IValue
{
    public uint ConstructorId => 0xAB73BAE1;
    public TVector<MyTelegram.Schema.E2e.IPersonalOnClient> Entries { get; set; }

    public void ComputeFlag()
    {

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Entries);
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        Entries = reader.Read<TVector<MyTelegram.Schema.E2e.IPersonalOnClient>>();
    }
}