// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema.E2e;


[TlObject(0x6CA0713)]
public sealed class TValueContactByUserId : IValue
{
    public uint ConstructorId => 0x6CA0713;
    public TVector<byte[]> PublicKeys { get; set; }

    public void ComputeFlag()
    {

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(PublicKeys);
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        PublicKeys = reader.Read<TVector<byte[]>>();
    }
}