// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema;

///<summary>
/// See <a href="https://corefork.telegram.org/constructor/disallowedGiftsSettings" />
///</summary>
[TlObject(0x71f276c4)]
public sealed class TDisallowedGiftsSettings : IDisallowedGiftsSettings
{
    public uint ConstructorId => 0x71f276c4;
    public BitArray Flags { get; set; } = new BitArray(32);
    public bool DisallowUnlimitedStargifts { get; set; }
    public bool DisallowLimitedStargifts { get; set; }
    public bool DisallowUniqueStargifts { get; set; }
    public bool DisallowPremiumGifts { get; set; }

    public void ComputeFlag()
    {
        if (DisallowUnlimitedStargifts) { Flags[0] = true; }
        if (DisallowLimitedStargifts) { Flags[1] = true; }
        if (DisallowUniqueStargifts) { Flags[2] = true; }
        if (DisallowPremiumGifts) { Flags[3] = true; }
    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Flags);

    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        Flags = reader.ReadBitArray();
        if (Flags[0]) { DisallowUnlimitedStargifts = true; }
        if (Flags[1]) { DisallowLimitedStargifts = true; }
        if (Flags[2]) { DisallowUniqueStargifts = true; }
        if (Flags[3]) { DisallowPremiumGifts = true; }
    }
}