// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema;

///<summary>
/// See <a href="https://corefork.telegram.org/constructor/starGiftUnique" />
///</summary>
[TlObject(0x6411db89)]
public sealed class TStarGiftUnique : IStarGift
{
    public uint ConstructorId => 0x6411db89;
    public BitArray Flags { get; set; } = new BitArray(32);
    public long Id { get; set; }
    public string Title { get; set; }
    public string Slug { get; set; }
    public int Num { get; set; }
    public MyTelegram.Schema.IPeer? OwnerId { get; set; }
    public string? OwnerName { get; set; }
    public string? OwnerAddress { get; set; }
    public TVector<MyTelegram.Schema.IStarGiftAttribute> Attributes { get; set; }
    public int AvailabilityIssued { get; set; }
    public int AvailabilityTotal { get; set; }
    public string? GiftAddress { get; set; }
    public long? ResellStars { get; set; }

    public void ComputeFlag()
    {
        if (OwnerId != null) { Flags[0] = true; }
        if (OwnerName != null) { Flags[1] = true; }
        if (OwnerAddress != null) { Flags[2] = true; }
        if (GiftAddress != null) { Flags[3] = true; }
        if (/*ResellStars != 0 &&*/ ResellStars.HasValue) { Flags[4] = true; }
    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Flags);
        writer.Write(Id);
        writer.Write(Title);
        writer.Write(Slug);
        writer.Write(Num);
        if (Flags[0]) { writer.Write(OwnerId); }
        if (Flags[1]) { writer.Write(OwnerName); }
        if (Flags[2]) { writer.Write(OwnerAddress); }
        writer.Write(Attributes);
        writer.Write(AvailabilityIssued);
        writer.Write(AvailabilityTotal);
        if (Flags[3]) { writer.Write(GiftAddress); }
        if (Flags[4]) { writer.Write(ResellStars.Value); }
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        Flags = reader.ReadBitArray();
        Id = reader.ReadInt64();
        Title = reader.ReadString();
        Slug = reader.ReadString();
        Num = reader.ReadInt32();
        if (Flags[0]) { OwnerId = reader.Read<MyTelegram.Schema.IPeer>(); }
        if (Flags[1]) { OwnerName = reader.ReadString(); }
        if (Flags[2]) { OwnerAddress = reader.ReadString(); }
        Attributes = reader.Read<TVector<MyTelegram.Schema.IStarGiftAttribute>>();
        AvailabilityIssued = reader.ReadInt32();
        AvailabilityTotal = reader.ReadInt32();
        if (Flags[3]) { GiftAddress = reader.ReadString(); }
        if (Flags[4]) { ResellStars = reader.ReadInt64(); }
    }
}