// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema;

///<summary>
/// See <a href="https://corefork.telegram.org/constructor/inputInvoiceStarGiftUpgrade" />
///</summary>
[TlObject(0x4d818d5d)]
public sealed class TInputInvoiceStarGiftUpgrade : IInputInvoice
{
    public uint ConstructorId => 0x4d818d5d;
    public BitArray Flags { get; set; } = new BitArray(32);
    public bool KeepOriginalDetails { get; set; }
    public MyTelegram.Schema.IInputSavedStarGift Stargift { get; set; }

    public void ComputeFlag()
    {
        if (KeepOriginalDetails) { Flags[0] = true; }

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Flags);
        writer.Write(Stargift);
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        Flags = reader.ReadBitArray();
        if (Flags[0]) { KeepOriginalDetails = true; }
        Stargift = reader.Read<MyTelegram.Schema.IInputSavedStarGift>();
    }
}