// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema;

///<summary>
/// See <a href="https://corefork.telegram.org/constructor/inputInvoicePremiumGiftStars" />
///</summary>
[TlObject(0xdabab2ef)]
public sealed class TInputInvoicePremiumGiftStars : IInputInvoice
{
    public uint ConstructorId => 0xdabab2ef;
    public BitArray Flags { get; set; } = new BitArray(32);
    public MyTelegram.Schema.IInputUser UserId { get; set; }
    public int Months { get; set; }
    public MyTelegram.Schema.ITextWithEntities? Message { get; set; }

    public void ComputeFlag()
    {
        if (Message != null) { Flags[0] = true; }
    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Flags);
        writer.Write(UserId);
        writer.Write(Months);
        if (Flags[0]) { writer.Write(Message); }
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        Flags = reader.ReadBitArray();
        UserId = reader.Read<MyTelegram.Schema.IInputUser>();
        Months = reader.ReadInt32();
        if (Flags[0]) { Message = reader.Read<MyTelegram.Schema.ITextWithEntities>(); }
    }
}