// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema;

///<summary>
/// See <a href="https://corefork.telegram.org/constructor/webPageAttributeUniqueStarGift" />
///</summary>
[TlObject(0xcf6f6db8)]
public sealed class TWebPageAttributeUniqueStarGift : IWebPageAttribute
{
    public uint ConstructorId => 0xcf6f6db8;
    public MyTelegram.Schema.IStarGift Gift { get; set; }

    public void ComputeFlag()
    {

    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Gift);
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        Gift = reader.Read<MyTelegram.Schema.IStarGift>();
    }
}