// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema;

///<summary>
/// Forwarded document
/// See <a href="https://corefork.telegram.org/constructor/inputMediaDocument" />
///</summary>
[TlObject(0xa8763ab5)]
public sealed class TInputMediaDocument : IInputMedia
{
    public uint ConstructorId => 0xa8763ab5;
    ///<summary>
    /// Flags, see <a href="https://corefork.telegram.org/mtproto/TL-combinators#conditional-fields">TL conditional fields</a>
    ///</summary>
    public BitArray Flags { get; set; } = new BitArray(32);

    ///<summary>
    /// Whether this media should be hidden behind a spoiler warning
    /// See <a href="https://corefork.telegram.org/type/true" />
    ///</summary>
    public bool Spoiler { get; set; }

    ///<summary>
    /// The document to be forwarded.
    /// See <a href="https://corefork.telegram.org/type/InputDocument" />
    ///</summary>
    public MyTelegram.Schema.IInputDocument Id { get; set; }
    public MyTelegram.Schema.IInputPhoto? VideoCover { get; set; }
    public int? VideoTimestamp { get; set; }

    ///<summary>
    /// Time to live of self-destructing document
    ///</summary>
    public int? TtlSeconds { get; set; }

    ///<summary>
    /// Text query or emoji that was used by the user to find this sticker or GIF: used to improve search result relevance.
    ///</summary>
    public string? Query { get; set; }

    public void ComputeFlag()
    {
        if (Spoiler) { Flags[2] = true; }
        if (VideoCover != null) { Flags[3] = true; }
        if (/*VideoTimestamp != 0 && */VideoTimestamp.HasValue) { Flags[4] = true; }
        if (/*TtlSeconds != 0 && */TtlSeconds.HasValue) { Flags[0] = true; }
        if (Query != null) { Flags[1] = true; }
    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Flags);
        writer.Write(Id);
        if (Flags[3]) { writer.Write(VideoCover); }
        if (Flags[4]) { writer.Write(VideoTimestamp.Value); }
        if (Flags[0]) { writer.Write(TtlSeconds.Value); }
        if (Flags[1]) { writer.Write(Query); }
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        Flags = reader.ReadBitArray();
        if (Flags[2]) { Spoiler = true; }
        Id = reader.Read<MyTelegram.Schema.IInputDocument>();
        if (Flags[3]) { VideoCover = reader.Read<MyTelegram.Schema.IInputPhoto>(); }
        if (Flags[4]) { VideoTimestamp = reader.ReadInt32(); }
        if (Flags[0]) { TtlSeconds = reader.ReadInt32(); }
        if (Flags[1]) { Query = reader.ReadString(); }
    }
}