// <auto-generated/>
// ReSharper disable All

namespace MyTelegram.Schema;

///<summary>
/// See <a href="https://corefork.telegram.org/constructor/starGiftAttributeOriginalDetails" />
///</summary>
[TlObject(0xe0bff26c)]
public sealed class TStarGiftAttributeOriginalDetails : IStarGiftAttribute
{
    public uint ConstructorId => 0xe0bff26c;
    public BitArray Flags { get; set; } = new BitArray(32);
    public MyTelegram.Schema.IPeer? SenderId { get; set; }
    public MyTelegram.Schema.IPeer RecipientId { get; set; }
    public int Date { get; set; }
    public MyTelegram.Schema.ITextWithEntities? Message { get; set; }

    public void ComputeFlag()
    {
        if (SenderId != null) { Flags[0] = true; }
        if (Message != null) { Flags[1] = true; }
    }

    public void Serialize(IBufferWriter<byte> writer)
    {
        ComputeFlag();
        writer.Write(ConstructorId);
        writer.Write(Flags);
        if (Flags[0]) { writer.Write(SenderId); }
        writer.Write(RecipientId);
        writer.Write(Date);
        if (Flags[1]) { writer.Write(Message); }
    }

    public void Deserialize(ref SequenceReader<byte> reader)
    {
        Flags = reader.ReadBitArray();
        if (Flags[0]) { SenderId = reader.Read<MyTelegram.Schema.IPeer>(); }
        RecipientId = reader.Read<MyTelegram.Schema.IPeer>();
        Date = reader.ReadInt32();
        if (Flags[1]) { Message = reader.Read<MyTelegram.Schema.ITextWithEntities>(); }
    }
}